name: build

on: 
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Copy .env
        run: cp .env.production .env
      - run: yarn install
      - run: yarn test:unit
      - run: yarn build
      - name: Upload Files to Server
        uses: appleboy/scp-action@master
        with:
          host: swerky.me
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          rm: true
          overwrite: true
          source: "dist"
          target: "/sites/products.swerky.me/client/app"
