name: Deploy to Server

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: yarn install
      - uses: yarn test:unit
      - uses: yarn build