name: Deploy to Server

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - run: yarn test:unit
      - run: yarn build